nelmio_cors:
  defaults:
    origin_regex: false
    allow_origin: [ '*' ]
    allow_methods: [ 'GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE' ]
    allow_headers: [ '*' ]
    expose_headers: [ 'Link' ]
    max_age: 0
  paths:
    '^/':
      origin_regex: false
      allow_origin: [ '*' ]
      allow_methods: [ 'GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE' ]
      allow_headers: [ '*' ]
      expose_headers: [ 'Link' ]
      max_age: 0